---
- name: install required packages ocs inventory 
  apt: 
    name: 
      - mariadb-server
      - python-mysqldb
      - python3-mysqldb 
    state: present 
  tags: mariadb

- name: enable and start the service 
  service: 
    name: mysql 
    state: started 
    enabled: true 
  tags: mariadb
